FROM node:18-alpine

WORKDIR /app

COPY server/package*.json ./
RUN apk add --no-cache netcat-openbsd
RUN npm install
RUN npm install -g nodemon

COPY server/prisma ./prisma/
RUN npx prisma generate

COPY server/scripts ./scripts

COPY server/entrypoint.sh /app/entrypoint.sh
RUN chmod +x /app/entrypoint.sh

COPY server/ ./

EXPOSE 5000

CMD ["/app/entrypoint.sh"]
