FROM node:18-alpine

WORKDIR /app

COPY client/package*.json ./
RUN npm install
RUN npm install --save-dev @types/node

ENV VITE_API_URL=http://localhost:5000/api
ENV NODE_ENV=development

EXPOSE 3000

CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0"]
